### ISSUE TITLE
Who is using?

### ISSUE THREAD

**Issue by medcl** [medcl/infini-gateway#20]
If you are using **INFINI GATEWAY** and happy to tell others that you are using, please leave message to here, I'd happy to add you to the section `Who is using` in documention, Thanks :)

Format:
Company/Organization: Your Comapny Name
Logo: A url link or attachement of your company/orgainization logo.
[Optional]  Comments: Some favourite words for INFINI Gateway.
[Optional]  Use case:  How's your use case?

**Comment by quietStrength** [comment]
hello medcl

   I am testing your infini gateway,thks very much. Now I have a problem : while I send a bulk request to ES cluster .it returns with mediaType "application/json; charset=UTF-8",but infini gateway return me "text/plain; charset=utf-8" . how config? I want infini-gateway  doesnot change the mediaType, Thank you for your reply

**Comment by singgel** [comment]
Company/Organization: xueqiu
Logo: https://xueqiu.com/
Comments:  simple and feature rich
Use case: log management

**Comment by medcl** [comment]
Moved to: https://github.com/infinilabs/gateway/discussions/3
