### ISSUE TITLE
啥时候有空，大神来整个配置文件的详细功能文档啊，试用不会配置，太难了。。

### ISSUE THREAD

**Issue by huangpeng0817** [medcl/infini-gateway#21]
啥时候有空，大神来整个配置文件的详细功能文档啊，试用不会配置，太难了。。
想测试，配置没有搞懂。。

**Comment by medcl** [comment]
正在码，可以先看看社区的几篇试用文章：
https://elasticsearch.cn/article/14165

**Comment by medcl** [comment]
文档已上线，不断更新中。
http://gateway.infini.ltd/
