### ISSUE TITLE
文档中配置网关菜单打不开。

### ISSUE THREAD

**Issue by huangpeng0817** [medcl/infini-gateway#22]
操作文档中配置网关菜单页打不开。功能手册中的流程处理里面参数说明使用的是服务入口的。。是不是不对呀.
服务入口怎么对应后面es集群的多个环境，例如 dev beta 等，之前测试中，不知道咋配置，什么参数字段是关联到指定es集群的

**Comment by medcl** [comment]
文档还在完善更新中，你重新刷新一下看看呢？
