### ISSUE TITLE
elasticsearch的endpoint支持写多个吗

### ISSUE THREAD

**Issue by hbzhu** [medcl/infini-gateway#29]
比如支持如下的写法吗？
elasticsearch:
- name: prod
  enabled: true
  endpoint: http://192.168.3.201:9200,http://192.168.3.202:9200,http://192.168.3.203:9200

若是不行，那我岂不是还是要加个nginx或者lvs

**Comment by medcl** [comment]
答案是不需要多个，Elasticsearch 模块会自动发现集群所有的节点，并且会自动更新后端拓扑，只是在启动程序的时候才会从配置的这个地址去进行连接获取集群信息。

**Comment by hbzhu** [comment]
明白，打开了discover是可以拿到后端的node，不过得祈祷我启动gateway的时候配置的node没有挂掉

**Comment by medcl** [comment]
嗯，真遇到了，那就启动的时候改改吧，我后续再完善这块的处理。

**Comment by hbzhu** [comment]
谢谢大佬
