### ISSUE TITLE
查询gateway报错maxMsgSize大小超出限制

### ISSUE THREAD

**Issue by BigDataPeng** [medcl/infini-gateway#31]
查询索引数据,返回的消息体太大,gateway报错 invlid message write size (102493489) maxMsgSize=104857600,消息体默认的是100M,而我返回的数据大于了100M,建议增加修改此配置的参数.

**Comment by medcl** [comment]
有的，改这个。
![image](https://user-images.githubusercontent.com/64487/109143084-9ac1e780-779a-11eb-9ee9-f986b267a04b.png)
