### ISSUE TITLE
gateway如何配置url-pattern来实现es的通配查询？

### ISSUE THREAD

**Issue by sky111111** [medcl/infini-gateway#32]
例如满足下面这种语句
curl  localhost:8000/aaa@*/_search?pretty

我配置的时候，老是报这种错误信息

wildcards must be named with a non-empty name in path '/aaa*'

**Comment by medcl** [comment]
*？暂时还不支持，回头加上，目前支持:name 来代替*，如下：
![image](https://user-images.githubusercontent.com/64487/109475784-12e91f80-7ab1-11eb-9f8a-45bc66d3f891.png)
