### ISSUE TITLE
必须直连es集群，无法使用代理地址

### ISSUE THREAD

**Issue by daiyongjun** [medcl/infini-gateway#33]
目前公司使用的是阿里云提供的ES服务，阿里云提供的ES服务，对外暴露的地址是代理服务的地址，导致小公司可能无法使用该网关

**Comment by medcl** [comment]
如果只有一个 es 集群的话，那就只能使用除后端负载的其他功能，discover 可以关闭，缓存和限速限流还是可以用的。
