### ISSUE TITLE
代理多集群

### ISSUE THREAD

**Issue by MrLiukang** [medcl/infini-gateway#36]
你好，目前我们多集群有多个，使用了searchguard和x-pack做的认证，目前的使用是分别登录两个kibana去访问数据，现在的想法是通过登录一个kibana界面去访问两个集群的数据，想知道如何去做。我试过了好多次，每次访问kibana的时候都告诉 `Kibana server is not ready yet` 。
我目前的想法是:
                                 |--->cluster1
kibana-->gateway |
                                 |--_>cluster2

**Comment by medcl** [comment]
这个多集群查询倒是可以实现的

**Comment by medcl** [comment]
新版本已支持。http://gateway.infini.sh/docs/references/filters/switch/
[gateway-linux.zip](https://github.com/medcl/infini-gateway/files/6304425/gateway-linux.zip)
