### ISSUE TITLE
双写为啥只返回最后一个的结果

### ISSUE THREAD

**Issue by lumian2015** [medcl/infini-gateway#39]
你好，我看到你写的文档里面说，double-write 只会返回最后一个的结果，但是如果出现这样一种情况，比如第一个集群写入失败，第二个集群写入成功了，这样如果返回成功，会让 client 误以为双写成功了，但是实际情况却不是，不知道对于这样类似的情况，infini-gateway 是否打算兼容呢？

BTW，我发现从 github 上下载下来的源码，没有能找到 filter 相关的代码，编译出来的也跟 release 的不一样。请问是这部分没有 publish 还是在具体哪个代码中了，希望能够告知一下，我也好学习一下相关代码的实现，谢谢！

**Comment by medcl** [comment]
之前的双写比较简单，没有处理异常的情况，请下载最新的版本，里面提供了双集群互备的配置 http://release.elasticsearch.cn/gateway/snapshot/gateway-1.2.0_SNAPSHOT-232-linux64.tar.gz，后端两个集群可以随便挂，都没问题的。

**Comment by lumian2015** [comment]
好的，谢谢！那请问一下代码部分的问题可以帮忙回答一下吗。我们 ES 团队是看到你写的这个 Proxy 感觉很好，想用你写的这个 Proxy，但是有些功能特性想据此改造一下，比如说上面说的双写的异常处理，比如配置的位置等。但是我没能找到对应的源码位置，是我没找到还是说放在别的仓库了，再次感谢！

**Comment by medcl** [comment]
恩，源码完善中，暂时没有同步上来，可以先试用一下提供反馈意见。

**Comment by lumian2015** [comment]
> 恩，源码完善中，暂时没有同步上来，可以先试用一下提供反馈意见。

好的，明白。请问一下是否有一个大概的计划，时间点呢？感谢！
