### ISSUE TITLE
新版本的文档更新

### ISSUE THREAD

**Issue by zhexy123** [medcl/infini-gateway#40]
大神，我看 http://release.elasticsearch.cn/gateway/stable/ 这个网址，最新稳定版出到了236版本，而另一个目录到了242版本，我下载了236，看了配置文件，发现多了一些在文档中找不到的内容，比如说 filter_v2 这种内容，还有set_basic_auth 这种过滤器。期待大神早日同步更新文档，能简单说一些新增的功能，就更好了，十分期待更新！

**Comment by medcl** [comment]
同 #41
