### ISSUE TITLE
k8s环境中如何实现该网关的热备机制

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [medcl/infini-gateway#43]
尝试了下，在k8s中 floating ip机制似乎无法正常工作（使用的overlay网络），floating ip在pod的container里具有隔离性，会导致两个节点都加上floating ip。如果用k8s来部署infini-gateway的话，应该如何来实现HA？

**Comment by medcl** [comment]
如果是k8s就依赖他本身的提供的这些高可用机制会更好一点哈。

**Comment by ZhiXingHeYiApple** [comment]
你的意思是pod数量可以部署成(>=2)，然后用service进行负载均衡就可以了？有个疑问的地方请教下：infini gateway的节点是完全无状态的吗？因为我看文档里还有bulk reshuffle功能，还可以配置成把文档先保存在本地磁盘队列里，这个特性会使gateway节点变成有状态的吗？而且gateway配置修改都需要重启pod，如果有3个pod，滚动更新的过程中，service的流量是按roubin路由策略的，如何保证流量是一次性切换过来的（active-standby模式可以保证）。

**Comment by ZhiXingHeYiApple** [comment]
我目前在k8s中的部署方式还是active-standy模式。使用Deployment或StatefulSet控制器托管2个pod，参考https://kubernetes.io/zh/blog/2016/01/11/simple-leader-election-with-kubernetes/，利用leader-elector镜像以sidecar模式实现gateway应用程序外选主逻辑，之后利用k8s的readiness健康检查机制实现流量只会路由到active pod。目前验证了可以按正确逻辑运行。

**Comment by medcl** [comment]
@ZhiXingHeYiApple 如果不使用本地磁盘队列就是无状态的，如果放了数据在本地了就最好确保处理消费完再移除 pod，不过目前  网关也支持 redis 作为队列了，如果使用 redis 可以理解为无状态。
另外如果要切换的话，也是没问题的，先把流量切走，网关如果本地有数据处理完了再移除就行了。

使用 redis 队列的方法：
```
#redis:
#  enabled: true
#  host: localhost
#  port: 6379
#
#queue:
#  - name: dev-node-yNgVusnXSgqvP2fZeGFSLw
#    type: redis
```
新增一条队列配置，将特定的队列名称 type 设置为 redis 就行了。
当前的队列情况，可以通过 API 来进行查看。http://localhost:2900/stats 和 http://localhost:2900/queue/stats

**Comment by ZhiXingHeYiApple** [comment]
@medcl 明白了，感谢大大耐心的解答
