### ISSUE TITLE
官网错误-ip限速描述是index限速

### ISSUE THREAD

**Issue by caster-Q** [medcl/infini-gateway#45]
![image](https://user-images.githubusercontent.com/27912584/131937017-7921b392-e759-410a-b778-d61be5849709.png)

**Comment by caster-Q** [comment]
![image](https://user-images.githubusercontent.com/27912584/131937410-a78b1545-f62f-42f8-b236-59f12cfe5c52.png)
请求响应

**Comment by caster-Q** [comment]
看了大佬新推的每日构建 gateway-docs-1.3.0_SNAPSHOT-72.zip ，已修改。

**Comment by medcl** [comment]
谢谢指正，已更新。

**Comment by caster-Q** [comment]
@medcl 有什么我们可以做的么？
另外请问大佬infini.sh什么时候PUSH上来，想和大佬一起学习，读一下项目源码

**Comment by medcl** [comment]
欢迎贡献一些使用案例和教程啊

**Comment by caster-Q** [comment]
好的
